### ISSUE TITLE
How to create a language lexer and parser for C # using `AntlrVSIX`?

### ISSUE THREAD

**Issue by it19862** [kaby76/AntlrVSIX#20]
I need an application that will syntax highlight the `C#` code and return text in `RTF` format.
To format the syntax of the `C #` code, I use the code:
 ```
 void changeLine(RichTextBox RTB, int line, Color clr, int curPos)
 {
    string testWords = @"\b(test1|test2)\b";
    MatchCollection testwordMatches = Regex.Matches(RTB.Lines[line], testWords);
 
    foreach (Match m in testwordMatches)
    {
        //RTB.SelectionStart = m.Index;
        //RTB.SelectionLength = m.Length;
        RTB.SelectionColor = Color.Blue;
    }
 
    RTB.SelectionStart = curPos;
    RTB.SelectionColor = Color.Black;
}
```
 
I studied the topic `Syntax highlighting richtextbox in C # on a single line only`
https://stackoverflow.com/questions/44378157/syntax-highlighting-richtextbox-in-c-sharp-on-a-single-line-only
I want to abandon the use of `Regex`.
For this, I plan to use Antlr.
 
**Used by:**
 - Visual Studio - 2019;
 
**I did:**
1. I installed `AntlrVSIX`;
2. I used the template `AntlrFAProject` (Net Framework);
3. I added the `Parsing` folder;
4. I added the file `CSharpLexer.g4`;
File Source - github.com/antlr/grammars-v4/tree/master/csharp
5. I pressed `F6`;
6. Result:
 - `Unknown build error:
Cannot find Antlr4 jar file, currently set to
'C: \ Program Files \ Java \ javalib \ antlr-4.7.2-complete.jar'
Please set either the Antlr4ToolPath environment variable,
or set a property for Antlr4ToolPath in your CSPROJ file.`


Questions.
1. How to fix a mistake?
2. Am I the right decision to get rid of "regular expressions"?

**PICTURE**
![2019-10-07_21-24-24](https://user-images.githubusercontent.com/18245828/66339442-d5c83e80-e94b-11e9-97cf-d4073cd6c496.png)

**Comment by kaby76** [comment]
It sounds like you don't have everything installed. Please check out the installation of Java and the Antlr tool here: https://github.com/kaby76/Antlr4BuildTasks#installation-of-prerequisites. Afterwards, follow the instructions in the next section https://github.com/kaby76/Antlr4BuildTasks#verify-prerequisites to verify that your environment, and the download/installed JDK and Antlr. You can also edit the .csproj file to set JAVA_HOME and/or Antlr4ToolPath with hardcoded paths, but try first to get the Antlr tool working at a command-line prompt. I'll update the instructions here because AntlrVSIX uses Antlr4BuildTasks for Antlr programs.

**Comment by it19862** [comment]
@kaby76  
Used Win-7x64

Could you write the first points in steps.
I follow the link.
The page says, "Install the Java toolkit, either OpenJDK, or Oracle JDK SE."
What exactly to do in my situation?
I follow the link "OpenJDK", there are still links ...
I go to those links, there are still links ...

![2019-10-08_14-03-53](https://user-images.githubusercontent.com/18245828/66391053-be816380-e9d4-11e9-9057-1a12cfa41731.png)


**AntlrConsl.csproj**
`<?xml` version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProductVersion>8.0.30703</ProductVersion>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>{D85546B5-B54E-4C5E-90DB-4FB08BFDA7A2}</ProjectGuid>
    <OutputType>Exe</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>AntlrConsl</RootNamespace>
    <AssemblyName>AntlrConsl</AssemblyName>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="CalculatorVisitor.cs" />
    <Compile Include="ErrorListener.cs" />
    <Compile Include="Output.cs" />
    <Compile Include="Program.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Antlr4 Include="arithmetic.g4" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.7.2" />
    <PackageReference Include="Antlr4BuildTasks" Version="1.0.7" />
    <PackageReference Include="Microsoft.CodeAnalysis" Version="3.3.1" />
  </ItemGroup>
  <ItemGroup>
    <Antlr4 Include="Parsing\CSharpLexer.g4" />
  </ItemGroup>
  <PropertyGroup Condition="'$(JAVA_HOME)'==''">
    <JAVA_HOME>C:\Program Files\Java\jdk-11.0.1</JAVA_HOME>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Antlr4ToolPath)'==''">
    <Antlr4ToolPath>C:\Program Files\Java\javalib\antlr-4.7.2-complete.jar</Antlr4ToolPath>
  </PropertyGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  
</Project>

**Comment by kaby76** [comment]
1) Open Google Chrome browser on Windows. Type in https://jdk.java.net/13/ in the address box.

2) Onhttps://jdk.java.net/13/, look for "Windows / x64" and the text "zip" hyperlinked there. Click on "zip".

3) A progress tab should open at the bottom of the Google Chrome window. Wait for the download to complete. It should be a file named "openjdk-13_windows-x64_bin.zip"

4) Click on the caret "^" for the downloaded file in the progress tab. Select in the pop-up "Show in Folder". That should pop open Windows Explorer on the .zip file. Otherwise, just go to your Downloads directory in a Windows Explorer and look for the .zip file.

5) Right-click on the .zip file, and select "Extract all". That should pop open an Extract files dialog box to a directory. Click on "Extract". When it's finished it should pop open Windows Explorer on the OpenJDK directory. Select the directory there until you see "bin", "conf", "include", "lib", etc. Select the location in Windows Explorer and copy (or just write this directory down).

6) Following what you did to set the environmental variables, you need to now update JAVA_HOME in the *System Settings* to the path you just copied. If you have JAVA_HOME in both system settings and your user settings, I'd recommend you delete the user settings copy.

7) I'll assume you downloaded the Antlr jar file, and also updated the Env *SYSTEM SETTINGS* for the full path of the Antlr jar file for the env var named "Antlr4ToolPath".

8) Save and close all the dialog boxes, the browser, Windows Explorer, etc. Close everything. Reboot your machine. Login in. You have to reboot and login to get the new value of JAVA_HOME for Windows Explorer.

9) Open Windows Explorer. Type in %JAVA_HOME%. It should take you to the installation directory of OpenJDK.

10) Follow the steps on opening a command-line prompt, and verify you can run the Antlr Java tool using the environment variables. It's there at https://github.com/kaby76/AntlrVSIX#verify-prerequisites. 

If that works you're getting close. If it's not working, let me know, ken.domino@gmail.com. Let's take this offline here on.

11) If it works, then open VS2019, create a new Antlr app, and build it, then run.

**Comment by it19862** [comment]
@kaby76  
))))
Thanks for the detailed answer.

I have a question on "item 7".
Could you describe it in more detail?
But not as detailed as your post above. )))

**Comment by it19862** [comment]
"p.7" speaks about it?
https://github.com/kaby76/Antlr4BuildTasks#installation-of-prerequisites
`Downloaded the Java-based Antlr tool chain. Complete ANTLR 4.7.2 Java binaries jar.`

**Comment by kaby76** [comment]
* In a chrome browser,  download  [https://www.antlr.org/download/antlr-4.7.2-complete.jar](https://www.antlr.org/download/antlr-4.7.2-complete.jar). Make a note of the full path of the file, eg c:\users\..........\downloads\antlr-4.7.2-complete.jar.

* Update Antlr4ToolPath with this path. Reboot, then test at a command line prompt.

**Comment by it19862** [comment]
@kaby76  
Once again I want to check that I did everything right.
 
 1. Downloaded - "openjdk-13_windows-x64_bin.zip";
 2. "openjdk-13_windows-x64_bin.zip" unpacked into a folder - `c: \ Program Files \ Java \ jdk-13 \`
 In the folder `c: \ Program Files \ Java \ jdk-13 \`  is:
Folder - lib \
Folder - legal \
Folder - jmods \
Folder - include \
Folder - conf \
Folder - bin \
File - release
 
 3. Changed the value of the system variable `JAVA_HOME`.
 Result JAVA_HOME = `c:\Program Files\Java\ jdk-13\`;
 
 4. I checked: in the "User Environment Variables" the variable `JAVA_HOME` is not.
 
 5. I downloaded the file `antlr-4.7.2-complete.jar`.
 
 6. The file `antlr-4.7.2-complete.jar` is located in the folder -
`c: \ Program Files \ Java \ javalib \ antlr-4.7.2-complete.jar`
  
 7. My application is called `AntlrConsl`.
 8. I open the file `AntlrConsl.csproj`.
 I make changes.
 Result.
```
  <PropertyGroup Condition = "'$ (JAVA_HOME)' == ''">
    <JAVA_HOME> c: \ Program Files \ Java \ jdk-13 \ </JAVA_HOME>
  </PropertyGroup>
  <PropertyGroup Condition = "'$ (Antlr4ToolPath)' == ''">
    <Antlr4ToolPath> C: \ Program Files \ Java \ javalib \ antlr-4.7.2-complete.jar </Antlr4ToolPath>
  </PropertyGroup>
```
  
  8. Reboot the computer.

Did I understand correctly?

**Comment by it19862** [comment]
@kaby76 

See previous post.
Could you tell (or where to read) about `Antlr4ToolPath` in more detail.
In instruction
https://github.com/kaby76/AntlrVSIX#verify-prerequisites
meaning "Antlr4BuildTasks"?
Do I need to create the `Antlr4ToolPath` system variable myself?

**Comment by kaby76** [comment]
Sorry, that should be Antlr4ToolPath, not Antlr4BuildTasks. Yes, create a system variable for the full path of the downloaded Antlr .jar file, then give it a try. The Antlr4ToolPath is used in the Antlr .targets file, https://github.com/kaby76/Antlr4BuildTasks/blob/master/Antlr4BuildTasks/Antlr4BuildTasks.targets. That looks at those environmental variables and passes them along with other parameters to the tool (a C# class library with a method Execute() that msbuild.exe calls to do the build). The tool is just a wrapper for input and outputs, to make it play nice with msbuild.

**Comment by kaby76** [comment]
I'm going to close this issue with the changes I made to the instructions a couple of weeks ago. I can reopen if there's still a problem.
