### ISSUE TITLE
AntlrVSIX not showing up in extension menu (VS2019)

### ISSUE THREAD

**Issue by fubar-coder** [kaby76/AntlrVSIX#29]
Executing `"%JAVA_HOME%\bin\java.exe" -jar "%Antlr4ToolPath%"` works as expected and I don't get an exception when I start VS 2019. Is there something else I can do?

EDIT: Some system info.

Java (JDK): 13.0.2
Antlr: 4.8
Windows: 10 (1909)
VS 2019: 16.4.3

**Comment by kaby76** [comment]
Unfortunately, I removed the extension menu for the version 5.0 release. Much of the functionality is still there, but it is now implemented directly by the Visual Studio LSP Client API. E.g., to "go to def", right-click on the symbol (terminal or nonterminal) and select "go to definition" in the pop-up context menu. I will likely add some of the UI back in but it will be piecemeal--I'm not sure which yet. Unfortunately, I will need to duplicate some of the MS LSP client API in order to add it back to an extension menu.

**Comment by fubar-coder** [comment]
Oh, ok, I thought that there was a problem, because the syntax highlighting doesn't seem to work too.

**Comment by kaby76** [comment]
So "highlighting" should work--i.e., if you click on a symbol, then it should "highlight" the whole word, and all occurrences of it in the grammar. "Colorization" doesn't work because MS LSP Client doesn't implement it. I'm in the process of writing TextMate rules to add colorization back in. (TextMate is hard to understand, and this is perhaps why MS added colorization calls into the LSP spec, which isn't fully implemented.) Sorry for the regressions in functionality, but I really wanted an LSP client/server.

**Comment by kaby76** [comment]
Fixed. V5.8.
