### ISSUE TITLE
Highlighting colors do not work well with VS themes

### ISSUE THREAD

**Issue by lextm** [kaby76/AntlrVSIX#36]
In VS dark theme, the default Nonterminal color (Blue) Terminal color (Purple) can be hard to read.

In VS blue theme, the default Literal color (LightGreen) can be hard to read.

**Comment by kaby76** [comment]
Sorry, I should have picked some better defaults. Unfortunately for now you'll have to fix that using the extension options, or manually edit the .antlrvsixrc file in your home directory. Afterwards, close and then reopen the grammar file to then get the colors you set in the rc file. The colors thru the normal Visual Studio options do not function for LSP servers.

**Comment by lextm** [comment]
Oh, I opened this issue so that such can be tracked. No worry. Once I have some time to investigate further, I might send you pull requests.

**Comment by kaby76** [comment]
I'll probably set up two theme colors in the ~/.antlrvsixrc options file. To maintain some continuity, I'll try to choose the colors in Mike Lischke's VS Code extension or those in the Eclipse plugin for Antlr.

**Comment by lextm** [comment]
Well, there are a few items to consider,

1. Learn current VS theme, https://stackoverflow.com/questions/15920572/how-to-get-current-used-color-theme-of-visual-studio/17093071 so that per theme default colors can be provided, and users don't even need to change in most cases.
1. Add support for VS color scheme files, so users can import/export.

**Comment by kaby76** [comment]
Yes, I will try to implement both.

**Comment by kaby76** [comment]
This is just some background information on the topic. Colorization has not been easy to implement.

Let's first talk about the terminology of programming languages and grammars that we've been using for at least 60 years (40 years ago for me since my graduate schooling days). A grammar is a 4-tuple: <nonterminal symbols, terminal symbols, productions, start symbol>. In Antlr parser grammars, the nonterminals are symbols that begin with lowercase letters, and terminals either are string literals or symbols that begin with uppercase letters. In Antlr lexer grammars (or the lexer rules of a combined grammar), the notion of a nonterminal is flipped: nonterminals are now symbols that begin with an uppercase letter, and terminals are only string literals. In Antlr, there are also mode names and channel names in lexer grammars. In both Antlr grammars, comments, keywords, and punctuation are used to define the rest of the grammar.

Before implementing an LSP server for Antlr, Antlrvsix was implemented using the usual ITagger<ClassificationTag>/ITaggerProvider that Visual Studio provides in the VSSDK. In version 4 of Antlrvsix, I could even set the color of the Antlr grammar features. But, that was all abandoned because I wanted to move to an LSP implementation--because it could be used in any editor, like Visual Studio Code, Eclipse, or even Emacs.

The lexicon of describing a grammar has no corresponding names in Language Server Protocol. In other words, you will not find symbols called nonterminal, terminals, etc. When I asked about this from LSP folk, they said just reuse something like "variable". They did not want to generalize the spec to allow any lexicon for a language. In Antlrvsix, the LSP server I implemented currently maps lowercase names to SymbolKind.Variable, uppercase names to SymbolKind.Enum, mode to SymbolKind.Event, channel to SymbolKind.Object. I cannot name comments, keywords, and literals as LSP symbols because the MS VS2019 LSP client wants to provide other services with symbols, like "find all references"--which obviously cannot be applied to comments.

This would be fine if the MS VS2019 LSP would implement colorization for LSP symbols, but after writing the LSP server, I found out that MS did not implement any colorization in the LSP client.

When reading the [documentation about how to implement an LSP server for VS2019](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-an-lsp-extension?view=vs-2019) (actually VS2017, since the documentation has not been updated for 3 years), MS says to use TextMate for colorization. Unfortunately, this does not work well. I tried two different TextMate descriptions for Antlr, but they really suck. The problem is that TextMate requires a .tmLanguage file, which contains grammar rules specified in XML (yes, crappy XML) to pick out nonterminals, terminals, comments, etc., from an Antlr grammar. TextMate grammar rules are basically regular expressions. If they could work, the TextMate description would duplicate the grammar rules encoded in the parser in an LSP server. But, hello? A regular grammar is not as powerful as a context-free grammar.

So, to do colorization, I implemented an out-of-LSP API to ask the server for the complete list of features for a file, which sends back a list of comments, keywords, nonterminals, etc. Colorization is is implemented in the client-side using ITagger<ClassificationTag>/ITaggerProvider. The colors are set in the options file because I wanted something that could work in Visual Studio Code or Emacs.

**Comment by lextm** [comment]
Semantic highlighting (syntax highlighting based on language server) is coming, and Microsoft has a Node.js implementation as experiment,

https://github.com/microsoft/vscode-languageserver-node/blob/324d1039fef2b9622a9784c5cc49d9f6dfc11b65/protocol/src/protocol.sematicTokens.proposed.ts

So I believe you should stick to your language server based approach, but participate actively in the standardization process to make ANTLR syntax another important experiment. (I also have my own language server for another language, which I plan to add semantic highlighting support.)

Thanks for sharing your experience, and that's valuable.

**Comment by kaby76** [comment]
["Semantic highlighting"](https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview) sounds pretty much what I implemented already for Antlrvsix, which, basically, has existed in VS IDE for many, many years as IClassificationFormatMap. So, I am glad they are "discovering" how to define and apply an equivalence class over characters in a text file for a programming language.

However, what I do see is a repeated pattern here of trying to apply typical programming language structure and terminology, like "class", "variable", "namespace", etc., as the names of those equivalence classes. LSP should handle any computer language. I just wish they would agree on a way to describe the equivalence classes and not ever use "class", "variable", "namespace", etc. In an Antlr grammar, there is no such thing. The left-hand side symbol of a parser rule is a "defining occurrence of a nonterminal". The language server should define what these equivalence classes are, what to call them, give a long-winded textbook description of what it is, how they work (whether you can "get all references" or "go to the defintion" of the symbol), etc. I programmed this all into Antlrvsix.

I don't see the value trying to make equivalence classes consistent across programming languages. There are subtle differences in how a variable works across programming languages. In any case, the user needs to know what he/she is talking about when programming in that language. The user is going to want to pick stylistic properties such as color/font/font size/pitch/etc for the equivalence class so he/she can read and edit the file easily. It should be a property list for a given language.

If the LSP server returns a TextMate identifier, I'm afraid LSP is tying itself to that. Or, if the LSP server returns the name in a character map class IClassificationFormatMap, it ties the LSP server to that VS IDE.

I think I pointed this out to the LSP folk, but as usual, I am a nobody.

For this particular issue, what I think I will do is replace all the color selections in the options file with a mapping of how to draw those characters in an editor, e.g., "nonterminal definers have style properties of 'type' in VS2019". So, the user can [apply VS2019 themes](https://marketplace.visualstudio.com/items?itemName=ms-madsk.ColorThemeDesigner), mentioned [in the VS blog](https://devblogs.microsoft.com/visualstudio/theming-in-visual-studio-just-got-a-lot-easier/).

**Comment by kaby76** [comment]
https://github.com/kaby76/AntlrVSIX/commit/0f66a955e38352ed19bf0fd3930ba5d6050d68a5 (and others) to fix colorization of text. The Antlr options box now contains a mapping in the lower right of the Antlr grammar symbols into a selectable Visual Studio "Display Item". When tagging text, I check the "Display Item" map, then set the color and text font for the text based on this map. The default values should be readable for whatever theme is currently in use.

**Comment by kaby76** [comment]
Version 7.2 should fix this problem. Let me know if that doesn't work for you. --Ken
